from .py.image_kontext_save_T import (
    NODE_CLASS_MAPPINGS as IMAGE_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_NAMES
)

from .py.shanzhu_depth_tif import (
    NODE_CLASS_MAPPINGS as DEPTH_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DEPTH_NODE_NAMES
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(IMAGE_NODE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DEPTH_NODE_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_NODE_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(DEPTH_NODE_NAMES)

print("✅ ComfyUI_SZtools nodes registered successfully.")
